//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP033095
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int scheduleId { get; set; }
        public string departureTime { get; set; }
        public string arrivalTime { get; set; }
        public string destination { get; set; }
        public int Ship_shipId { get; set; }
    
        public virtual Ship Ship { get; set; }
    }
}
