//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP033095
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int shipmentId { get; set; }
        public string shipmentType { get; set; }
        public string shipmentInsuredValue { get; set; }
        public string shipmentWeight { get; set; }
        public string shipmentDestination { get; set; }
        public string shipmentStatus { get; set; }
        public int Yard_yardId { get; set; }
        public int Customer_customerId { get; set; }
        public int Ship_shipId { get; set; }
    
        public virtual Yard Yard { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Ship Ship { get; set; }
    }
}
